import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navber from "@/components/layout/Navber";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({

  weight: ["100",'200','400','500','600','700','800','900'],
})

export const metadata = {
  title: "Hero-Kidzs App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} antialiased`}
    >
      <body className="py-2 md:max-w-11/12 mx-auto">
        
        <header className="py-2">
          <Navber />
        </header>

        <main>
          {children}
        </main>

        <footer className="py-2">
          <Footer />
        </footer>

      </body>
    </html>
  );
}
