import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navber from "@/components/layout/Navber";
import Footer from "@/components/layout/Footer";
import localFont from 'next/font/local'


const poppins = Poppins({

  weight: ["100",'200','400','500','600','700','800','900'],
})

export const FontBangla = localFont({
  src: './../fonts/mayaboti-normal.ttf',
})

export const metadata = {
  title: "Hero-Kidzz E-commerce Website",
  description: "Generated by create next app",
};  

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} antialiased`} 
    >
      <body className="">
        
        <header className="py-2 md:max-w-11/12 mx-auto">
          <Navber />
        </header>

        <main className="md:max-w-11/12 mx-auto min-h-[calc(100vh-335px)]">
          {children}
        </main>

        <footer className="py-2">
          <Footer />
        </footer>

      </body>
    </html>
  );
}
